### ISSUE TITLE
Test on dHCP image

### ISSUE THREAD

**Issue by federica28** [koopa31/SegSRGAN#3]
Hello!
I have tested with the script seg.py the super resolution reconstruction and segmentation on the **first patient** of the dHCP dataset. The low resolution (LR) image has been obtained thanks to the module Resample Scalar Volume of 3DSlicer, setting linear interpolation and spacing equal to 0.5x3x0.5 in order to get LR image with axial orientation. I have used weights with no data augmentation, patch=128 and step=30. By comparing the obtained SR volume with the original high resolution volume i have noticed that the brain volume of the first one is bigger than the second one. How does it possible? I have repeated the test also with neonatal clinical images (with weights=Perso_with_constrast_0.5_and_noise_0.03_val_max) but the problem still exists. 
I would like also to ask you if it's possible to have the email address of one of the author for further questions. 
Thank you!
[SR.nii.gz](https://github.com/koopa31/SegSRGAN/files/3707592/SR.nii.gz)
[LR.nii.gz](https://github.com/koopa31/SegSRGAN/files/3707595/LR.nii.gz)

**Comment by Qdelannoy** [comment]
Hello ! 

Yes the dHCP HR image have 203 slices on the z dimension (coronal). You expected 3Dslicer to change the z resolution from 0.5mm to  3mm which imply a downsampling with a 1/6 factor. 

However, 203 is not a multiple of 6, so the closer integer for the LR dimension is 34 (which is the z dimension of your LR image).

Finally, when the method is applied on this LR image to make super-resolution from 3 to 0.5,  the z dimension becomes 6 * 34 = 204.

If you want to be sure to have the same dimension for the High Resolution image and for the SR image, you need to crop or padd your image to get each dimension multiple of the upsampling you want to process. Which implies in your case to crop the image to get z dimension equal to 198 or padd the image to get z dimension equal to 204.
